[server]
headless = true
address = "0.0.0.0"
port = 5000
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#E20600"
backgroundColor = "#0A0F16"
secondaryBackgroundColor = "#131E2F"
textColor = "#FFFFFF"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = true
